### ISSUE TITLE
Issues with the unauthorized page

### ISSUE THREAD

**Issue by ale-rt** [plone/plone.org#101]
As anonymous I tried to visit:

- https://plone.org/news-and-events/news/2023/alpine-city-strategic-sprint-2023-news

and I got:
![image](https://user-images.githubusercontent.com/1300763/219689788-d9dec5f0-2b67-489d-b304-3a2d661432a8.png)

The links in `nav.navigation.navigation-dropdownmenu .ui.secondary.pointing.menu` are then clickable but they do not expand.

I was expecting:

1. the login page to appear
2. to be able to open the menus and browse somewhere else

**Comment by rioksane** [comment]
Now the news item is edited and published.
