### ISSUE TITLE
Replacing the "Download" section with an "Installation" section

### ISSUE THREAD

**Issue by SaiRev0** [plone/plone.org#103]
With reference plone/training#723

Thinking of Replacing the "Download" { [Download](https://plone.org/download) } section with an "Installation" { [Installation](https://6.docs.plone.org/install/index.html) } section as having the backend as a docker container is the way moving forward so we should update this here as well

**Comment by rioksane** [comment]
I renamed the main menu item from Download Plone to Install Plone. The page itself already was titled Installing Plone. I removed redundand stuff about trying Plone from the installation page. 

Though the url is still https://plone.org/download
That could be renamed without breaking links (thanks to Plone). 

Maybe a comment from @Fosten do you think that would be ok?

**Comment by Fosten** [comment]
Makes sense.  Note however https://plone.org/download/releases and https://plone.org/download/release-schedule/ are important to highlight.

**Comment by Fosten** [comment]
I would recommend solving this by replacing https://plone.org/get-started/download-plone link with a https://plone.org/get-started/install-plone page and then referencing the existing download folder within the new install content. This approach breaks the least amount of old links. To make a pretty url like plone.org/install could then add a redirect link. Or vice versa create the /install page and make /get-started/install-plone the redirect link.

**Comment by rioksane** [comment]
Added links to releases and release schedule and roadmap top plone installation page: https://plone.org/download. 

No need to rename the link thanks to link object. I'll close the issue.
