### ISSUE TITLE
Typo found in idea list

### ISSUE THREAD

**Issue by Vansh-Baghel** [plone/plone.org#104]
**Describe the bug**
There is a typing mistake in the idea list website. The Markdown link is looking like normal text. 

**To Reproduce**
Replace : (TanStack Query)[https://tanstack.com/query] 
With : [TanStack Query](https://tanstack.com/query)

Link : https://plone.org/community/gsoc/2023

**Screenshots**
![gg1](https://user-images.githubusercontent.com/103327712/224080008-0601b427-79eb-4323-b13c-d856ae25235a.png)

**Software (please complete the following information):**

- Volto Version [e.g. 8.5.0]
- Plone Version [e.g. 5.2.2]
- Plone REST API Version [e.g. 7.0.1]

**Additional context**

**Comment by AbhishekCS3459** [comment]
@Vansh-Baghel I can solve this issue please assign it to me.

**Comment by Vansh-Baghel** [comment]
> @Vansh-Baghel I can solve this issue please assign it to me.

This part is not from this repository. We would have to wait for developers' response for it.

**Comment by stevepiercy** [comment]
Wrong repo. Please open an issue in https://github.com/plone/plone.org

**Comment by davisagli** [comment]
@stevepiercy In case you didn't know, you can transfer an issue to the correct repo using the "Transfer issue" link in the right sidebar.

**Comment by stevepiercy** [comment]
@davisagli I tried, but plone.org is not listed for some reason. Perhaps I lack sufficient access to that repo? Do you have access?

**Comment by davisagli** [comment]
@stevepiercy Transferred and reopened.

@ericof Could you give @stevepiercy access to the plone.org repo please?

**Comment by Vansh-Baghel** [comment]
> Wrong repo. Please open an issue in https://github.com/plone/plone.org

Isn't this link for this repo itself?
I didn't find this text in any of the 2 repos (plone/plone.org and plone/volto)

**Comment by stevepiercy** [comment]
@Vansh-Baghel this issue was transferred, along with its history.

You won't find the text because it is stored in a database. plone.org uses Plone, after all. It requires someone with permission to edit the page.

**Comment by Vansh-Baghel** [comment]
> @Vansh-Baghel this issue was transferred, along with its history.
> 
> You won't find the text because it is stored in a database. plone.org uses Plone, after all. It requires someone with permission to edit the page.

Understood!! Do make the required change by informing them. 😇

**Comment by stevepiercy** [comment]
That is what this issue has done. No further action is required by you. Thank you!

**Comment by rioksane** [comment]
Thanks, the link is now fixed.
