### ISSUE TITLE
Quick to solve styling issues: header dropdown, centered h2, collapsing paragraph margins below lists.

### ISSUE THREAD

**Issue by fredvd** [plone/plone.org#110]
There are some visual styling issues that are really annoying me and that I'd like to fix or assist other frontenders to fix. They don't seem difficult, but do impact the visuals, so I want to gather some feedback first:

###  main menu drop down

The drop down menu on deskto lets you travel all diagonally over the screen to select a sub menu item. Why aren't these expanded right below the menu item ietself?

![Image](https://user-images.githubusercontent.com/394784/228587112-3a8109a4-2434-4eea-8fe5-15acc7f02d0c.png)

###  H2's are centered on the screen, all other head lines are not

What I see now in the content that h1 is the headline and editors use h3's for all sub headlines, because the centered h2 stands out as 'odd' most of the time. Can't we keep the headlines as they are left aligned and allow the centering to work instead if it's necessary visually? The problem is that a lot of old content now has centered subtitles on h2. 

![Image](https://user-images.githubusercontent.com/394784/228589382-706a0b27-a773-40d1-bc78-63b4e40d0db7.png)

### Links are not accessible and difficult to spot

For me the links in this screenshot are almost invisible. Can't we please underline them? Or have an expert figure out the colors for all possible combinations of color blindness? (read: that's almost impossible, just have underlines in the main content text. ) 

![Image](https://user-images.githubusercontent.com/394784/228589461-85124a8e-fbba-41aa-87aa-53f845f1f099.png)

**Comment by fredvd** [comment]
As discussed in the marketing meeting of march 29th 2023: 

* Menu can be made smaller if it is just one column that is the direct descendant.  The mobile menu has the same issue where the main categories are on the right, but on for example tablet view the sub-menus are also aligned on the left.
* h2 items can be aligned on the left.  sometimes it is visually nice to center a title, but shouldn't there be a center function for that in the toolbar?
* Links in the main text should all be underlined. There is apparently a closed issue for accessibility where this also was tuned, but it is still inaccessible for at lest me (and I have mild color blindness)

So go ahead to fix these issues on short notice.

**Comment by rioksane** [comment]
Miro has been working on this during midsummer sprint, will commit changes after contibutors agreement is ok.
