### ISSUE TITLE
Replace text of link to actual current link

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.org#112]
In https://plone.org/foundation/copyright-licensing-logo/license-faq, under the heading:

## Is Plone available under a dual-license?

There is outdated text for a link with `http` that needs to be updated.

```html
See our "Framework Components Relicensing Policy":http://plone.org/foundation/materials/foundation-resolutions/plone-framework-components-relicensing-policy
```

should be

```html
See our <a href="https://plone.org/foundation/about/materials/foundation-resolutions/plone-framework-components-relicensing-policy">Framework Components Relicensing Policy</a>
```

----------

Another link on:

https://plone.org/foundation/about/materials/foundation-resolutions/plone-framework-components-relicensing-policy#4669c6b3-5456-42bf-b3af-0a6bb9c583b9

[modified (aka. 3-clause) BSD license](http://www.opensource.org/licenses/bsd-license.php)

Should point to:

https://opensource.org/license/bsd-3-clause/

Refs: https://github.com/plone/documentation/pull/1478

**Comment by ericof** [comment]
Fixed

**Comment by stevepiercy** [comment]
The second link is fixed, but not the first. I cleared browser cache, but the first problem is still there.

![Screen Shot 2023-04-13 at 3 53 21 PM](https://user-images.githubusercontent.com/102112/231900177-a2289eff-cf62-4cb4-95f2-ccad58204ae2.png)

**Comment by ericof** [comment]
@stevepiercy Could you, please, check again?

**Comment by stevepiercy** [comment]
LGTM, thank you! Now it's up to the Board to revoke the dual-license policy. 😉 @fredvd

**Comment by ericof** [comment]
Closing the issue
