### ISSUE TITLE
Add custom View for Member profiles

### ISSUE THREAD

**Issue by Fosten** [plone/plone.org#119]
While the Plone Foundation may wish to collect members' contact info for internal purposes, plone.org shouldn’t display members' street address or email address on the website for privacy concerns.  Current member profiles are published and viewable anonymously.

Subsequently, without data to display, the default View clutters the pages with blank fields.

<img width="821" alt="Screen Shot 2023-05-11 at 1 06 11 PM" src="https://github.com/plone/plone.org/assets/1520484/a7592aa8-5d94-47ec-8f82-bff39034194e">

A custom View for Members would allow us to only show select fields with public data (such as contributions and social links), while keeping private data internal and unreachable for anonymous users/bots.

In general, this would allow us to design more visually appealing Member profiles.

**Comment by ericof** [comment]
We now have a custom view that only shows info to people with proper permissions
