### ISSUE TITLE
Link to 'Try Plone' not working

### ISSUE THREAD

**Issue by espenmn** [plone/plone.org#128]
The text link: 'Try Plone' is not correct/working on front page of plone.org .
The Button work (see screenshot=

**Comment by espenmn** [comment]
<img width="496" alt="Skjermbilde 2023-05-30 kl  13 32 14" src="https://github.com/plone/plone.org/assets/1069235/17c93b13-f12e-44f3-84fc-1393df7b69be">

**Comment by pbauer** [comment]
Fixed
