### ISSUE TITLE
sponsors and providers pages could use some visual help

### ISSUE THREAD

**Issue by tkimnguyen** [plone/plone.org#140]
https://plone.org/foundation/sponsorship/sponsors and https://plone.org/services/providers could use some help with the visuals, specifically the logo sizes and spacing

**Comment by tkimnguyen** [comment]
related to #100

**Comment by rioksane** [comment]
@tkimnguyen both look good to me. Did you already fix them or is there some details that need fine tuning?

**Comment by tkimnguyen** [comment]
Thanks for checking @rioksane 👍 Yeah the pages look decent now. I think @ericof may have tweaked things in the meantime.
