### ISSUE TITLE
RSS feed for news is missing

### ISSUE THREAD

**Issue by MrTango** [plone/plone.org#152]
We had a RSS feed for news on plone.org, that is now missing with the new Volto site.
It would be nice to get it back, RSS is still useful and is getting a renaissance lately.

**Comment by jensens** [comment]
The feature is still there, all needed is a collection with feeds enabled. Now search block is not collection based. 
But adding a collection (which is still available in a Plone 6 (or at least can be made available) would be enough.
Ok, we need to put a link somewhere.

**Comment by Fosten** [comment]
Closing this issue as a duplicate of #105
