### ISSUE TITLE
Typo in the German Aerospace Center (DLR) article in why-plone page

### ISSUE THREAD

**Issue by Ayushhgupta39** [plone/plone.org#153]
The article about the German Aerospace Center (DLR) in the why-plone page has a spelling error where it states the the number of employees in the DLR is 10.000 which technically means 10 employees which is not correct. It should be 10,000 not 10.000. The full decimal should be replaced by a comma as it is making the data wrong.

Page URL: https://plone.org/why-plone/they-use-plone/german-aerospace-center-dlr

![image](https://github.com/plone/plone.org/assets/96309609/88ec114e-2e0a-4e16-a6bb-178678931fb8)

**Comment by davisagli** [comment]
This is partly a localization issue: in some countries/languages the comma is used as a separator here, and in some countries the period is used. We should at least make it consistent with the "1.3 billion euros", and I _think_ we use US English for plone.org, so I edited the page to fix it. Thanks for pointing it out.

**Comment by stevepiercy** [comment]
FTR, yes, American English, because the Plone Foundation is based in Delaware, USA, and is recognized as a 501(c)(3) charitable organization with the IRS in the USA. FYI docs also use American English for the same reason.

**Comment by Ayushhgupta39** [comment]
Okay 👍🏼
