### ISSUE TITLE
Where to post links to sites that use Volto?

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.org#154]
We have [Sponsors](https://plone.org/foundation/sponsorship) and [They Use Plone](https://plone.org/why-plone/they-use-plone). AFAIK, we do not have a long list of links of websites that use Plone or Volto.

We have an [open pull request in Volto](https://github.com/plone/volto/pull/5511#pullrequestreview-1776850702) that consolidates the list of links of Volto sites into Awesome Volto and removes them from the Volto `README.md`. To complete that PR we need to get an opinion from @plone/marketing-communications about where they would like to post such a list of links, if at all.

**Comment by skleinfeldt** [comment]
It seems to me that the right place is somewhere under [They Use Plone](https://plone.org/why-plone/they-use-plone). This is currently a new set of "success stories" plus the old plone.com "success stories". The structure probably needs a bit of rethinking to add a list of current sites. There is also the issue of how/whether to include a list of Classic sites too.

Is there a plan for keeping this list up to date?

**Comment by stevepiercy** [comment]
@skleinfeldt Awesome Volto has [a GitHub Workflow that validates links on every pull request](https://github.com/collective/awesome-volto/blob/master/.github/workflows/main.yaml). If someone from Marketing monitors that repo for merged pull requests that add new Volto sites, it would be a simple matter of copy-pasting the merged pull request changes, assuming that plone.org supports either Markdown parsing or pasting richtext.

**Comment by rioksane** [comment]
@stevepiercy I added https://plone.org/why-plone/they-use-plone/they-use-plone-6, and it was just a simple copypaste from awesome volto GitHub page. I changed the title to emphasize Plone 6, with a description that mentions Volto. 

But how to keep it updated. 

and @skleinfeldt, I think the same page could have a section for Plone 6 classic sites.

**Comment by skleinfeldt** [comment]
Agreed @rioksane. I suppose the only realistic way to keep it updated would be to have a quarterly marketing task to re-do the copy/paste. Or maybe the script that runs when sites are added to the Github page could send an email to marketing....

**Comment by rioksane** [comment]
I added a todo item to marketing team meeting notes. Lets start with quarterly/monthly checks and see if we can automate it at some point.

**Comment by stevepiercy** [comment]
> Or maybe the script that runs when sites are added to the Github page could send an email to marketing....

It checks all links on Awesome Volto, not just new websites.

I would suggest that if you want notifications to update plone.org, you could do what I do, watch pull requests on that repo:

![Screenshot 2024-01-19 at 12 40 42 PM](https://github.com/plone/plone.org/assets/102112/20e9a91f-3f81-44f0-9341-50859fa270fc)
