### ISSUE TITLE
How to Ask for Help needs revision

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.org#156]
I would like to revise the text on this page, but I lack sufficient privileges.

Most of these tips are irrelevant to the newcomers I help. It needs to focus on the things that newcomers must do and should not do.

Suggested text:

----

# How to ask for help

Use the [Plone Community Forum](https://community.plone.org/) to ask for help from our community volunteers.

There are also many professional [Plone service providers](https://plone.org/services/providers) that you may hire.

## Things to do

When posting to the Plone Community Forum, you must give sufficient information for others to reproduce and identify the cause of your issue. Help us to help you.

- **What do you expect to happen?**
- **What steps did you take?** Include the terminal session commands you issued and a link to the documentation you followed.
- **What did you observe?** Include complete tracebacks and error messages as text, surrounded by triple backticks (`` ``` ``).

## Things not to do

- Do not post [images of text or error messages](https://meta.stackoverflow.com/questions/285551/why-should-i-not-upload-images-of-code-data-errors).
- Do not @ individuals.

----

See also https://github.com/plone/plone.org/issues/155 to improve link contrast.

**Comment by rioksane** [comment]
@stevepiercy I gave you permissions to https://plone.org/community/support/how-to-ask-for-help/

I wonder if I should straight up give you more permissions in general.

**Comment by stevepiercy** [comment]
@rioksane I'm OK with more permissions. If I have questions about content, such as this one, I can raise an issue. If it is a typo or grammar mistake, I can just make a change. Please let me know. Thank you!

**Comment by stevepiercy** [comment]
Also I assume I can look at history of who edited the page, and ask them directly. @tkimnguyen @polyester can we huddle today to discuss?

**Comment by tkimnguyen** [comment]
Just saw your question

**Comment by tkimnguyen** [comment]
OK looking at https://plone.org/community/support/how-to-ask-for-help

**Comment by tkimnguyen** [comment]
Having been on the receiving end of many or most of the things the current page asks people not to do, I'd say they're still helpful. Could it be that you're not seeing their utility because people are seeing them and doing (or not doing) the things they suggest? I'm happy for you to add info to the page.

**Comment by stevepiercy** [comment]
I never see those issues that I suggest be removed in any Plone repo, Discord, or the Community Forum.

I see the number of comments that ask for support in an incomprehensible manner per week:

- Volto's issue tracker: 5
- All other issue trackers that I watch: 0 - 1
- Discord: 10
- Community Forum: 3

I would like a page that I can direct people toward where the content helps them to create a useful request for support in the Community Forum. I don't want to give them a lot of extra information, just the essentials. Less is more.

**Comment by stevepiercy** [comment]
@tkimnguyen let's wrap this up. Please respond.

**Comment by tkimnguyen** [comment]
I shouldn't block you on this. Please proceed! @rioksane will you grant Steve more permission on the site? @stevepiercy do you have sufficient permission to change what you need?

**Comment by stevepiercy** [comment]
Done. Thank you!
