### ISSUE TITLE
Contributor Agreement page sets expectation for too quick response

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.org#160]
## Page

https://plone.org/foundation/contributors-agreement

## Description

We get too many impatient newcomers who don't read some text or the last FAQ. We need to better set their expectations to align with the reality of our response time, especially during holidays and vacations.

I suggest the following changes.

```diff
- Please note that actually adding you to the relevant team(s) is still a manual task, performed by volunteers, and therefore may take a few hours or days.
+ Please note that the entire process is performed by volunteers, and therefore may take a week to complete.
```

Move "I signed the Agreement, but haven't been given access yet." to first FAQ. Update its text:

```diff
- Please allow a few days of response time; the handling of Contributor Agreements is done by volunteers. If you have issues, or for instance think you may have made a spelling error in your email or github username, contact [agreements@plone.org](mailto:agreements@plone.org)
+ Please allow a week for a response. Volunteers process the Contributor Agreements. If you have issues, such as making a spelling error in your email or GitHub username, contact [agreements@plone.org](mailto:agreements@plone.org).
```

See also https://github.com/plone/documentation/pull/1607

**Comment by rioksane** [comment]
Made the suggested changes and removed some redundant empty blocks from the page.
