### ISSUE TITLE
Update Install Plone 6 page content

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.org#162]
Our story for installing Plone has recently changed in documentation.

On https://plone.org/download, delete the following bullet points, allowing documentation to direct visitors to the right place, which is [Install](https://6.docs.plone.org/install/index.html):

* [Method 1: Install using containers](https://6.docs.plone.org/install/containers/index.html) - the easiest way to try out and deploy Plone 6.
* [Method 2: Install using packages](https://6.docs.plone.org/install/install-from-packages.html) - for developing custom applications, themes, and add-ons for Plone.

We do not encourage Method 1 any longer, and we expect to turn it into a recipe in a future PR.

**Comment by Manas-Kenge** [comment]
@stevepiercy could you please direct me to the location in the repo I can't find it

**Comment by stevepiercy** [comment]
@Manas-Kenge it's content on the website plone.org, not code in the repo. This task requires someone with sufficient access on the site to edit the content.

**Comment by tkimnguyen** [comment]
Where would people find installation instructions instead?

**Comment by stevepiercy** [comment]
Edited description.

**Comment by rioksane** [comment]
Removed the bullet points as suggested.
