### ISSUE TITLE
Recurring Events display incorrect recurring dates

### ISSUE THREAD

**Issue by Fosten** [plone/plone.org#167]
When a recurring event is created, Plone shows the correct dates for the recurrence span.
But displays the subsequent recurring event dates as one day off.

<img width="937" alt="plone-event-error" src="https://github.com/plone/plone.org/assets/1520484/c7690fe4-c432-44ac-a953-fa66ac9480e9">

In the edit form you can also see that Tuesday is selected but Monday is populated.

<img width="901" alt="Screen Shot 2024-04-04 at 10 44 03 AM" src="https://github.com/plone/plone.org/assets/1520484/fe651d33-fd83-43dc-9e7a-17f8b1c924db">

Default timezone for the portal is set to to Sao Paulo.  Sao Paulo is UTC-3 and I am UTC-4.  So I don't think the one hour difference is what's throwing it off a whole day.

Not sure why this is happening.

**Comment by stevepiercy** [comment]
This is due to the site having a default timezone (Brasilia) that is different from the event's. See:

- https://github.com/plone/plone.org/issues/151
- https://github.com/plone/plone.org/issues/141
- https://github.com/plone/Products.CMFPlone/issues/4115

I think this issue is a duplicate report.

**Comment by Fosten** [comment]
Thanks @stevepiercy for clarifying. I figured this might be a duplicate of the timezone issues but wasn't certain.

**Comment by stevepiercy** [comment]
Closing as duplicate.
