### ISSUE TITLE
Make footer look like it is in the design

### ISSUE THREAD

**Issue by rioksane** [plone/plone.org#17]
Footer looks different in the beta site https://beta.plone.org/ than in the [Mural design](https://app.mural.co/t/giallocobalto8457/m/giallocobalto8457/1645259793023/c238ab04deb233bf0e484745ff6813a32707d859?sender=e149f985-af18-4832-837d-ed2646939e42)

Also, it now has accessibility issues. 

This is the design: 
<img width="1337" alt="Screenshot 2022-11-12 at 18 11 30" src="https://user-images.githubusercontent.com/5127672/201483530-2c58fe02-f7e3-4176-aee5-63e4d22ad4a6.png">

The 4 columns and content on the beta site now are good. 

Content links need work, but making the visual changes is in the scope of this issue. 
Footer content is being decided here https://beta.plone.org/why-plone/footer-content

**Comment by rit-clone** [comment]
Hi @rioksane I would like to work on this issue, can you please assign it to me?

**Comment by mpeeters** [comment]
also there is no space between the content and the footer e.g. https://beta.plone.org/foundation/board/plone-foundation-board-for-2022-2023
