### ISSUE TITLE
Add Plone newsletter sign up page link to Plone.org footer 

### ISSUE THREAD

**Issue by rioksane** [plone/plone.org#182]
Add Plone newsletter sign up page link to Plone.org footer 
Under community column. Last on the list. 

Link title is: 
“Join the Plone newsletter” and link address is https://plone.org/news-and-events/join-the-plone-newsletter

Reference image:
<img width="1142" alt="Screenshot 2024-09-11 at 20 57 24" src="https://github.com/user-attachments/assets/e19f22ca-360d-4d19-9852-59a337da9352">

**Comment by stevepiercy** [comment]
I'd also suggest adding a link to News and Events page, something like this.

![Screenshot 2024-09-11 at 5 43 50 PM](https://github.com/user-attachments/assets/7f9c410d-e99e-4ec2-bb78-ba091d292b5e)

**Comment by Adityaadpandey** [comment]
assign this issue to me

**Comment by davisagli** [comment]
Fixed by #185
