### ISSUE TITLE
Dropdown menu is not visible in certain screen sizes

### ISSUE THREAD

**Issue by rioksane** [plone/plone.org#24]
Dropdown menu is not visible from 992px through 1329px width thus making site navigation impossible media query hides the hamburger. the culprit is https://github.com/media only screen and (max-width: 1329px) and (min-width: 992px) display: none!important

Example:
<img width="1267" alt="Screenshot 2022-11-06 at 17 21 04" src="https://user-images.githubusercontent.com/5127672/200179307-3b0ed66f-f8e2-4cbc-a111-f8c7de65b899.png">

**Comment by Fosten** [comment]
If you change https://github.com/collective/volto-dropdownmenu/blob/2296741efd15bd3730fe7e4cf7a2a101f62ec880/src/customizations/components/theme/Navigation/Navigation.jsx#L138 from div className="hamburger-wrapper mobile tablet only" to div className="hamburger-wrapper mobile tablet computer only" the hamburger will display in 992px through 1329px (anonymous) and 1072px through 1409px (logged in).

However, the volto-dropdownmenu Navigation.jsx is several commits behind volto's Navigation.jsx latest changes, so adding another template override may not be ideal.  Is there a better way?
