### ISSUE TITLE
Hotfixes appear empty

### ISSUE THREAD

**Issue by mauritsvanrees** [plone/plone.org#35]
For example: https://beta.plone.org/security/hotfix/20220128

**Comment by mpeeters** [comment]
The reason seems that there is no view on the frontend for this content, all the data are available in edit mode

**Comment by pbauer** [comment]
This one has not hotfix-file. It says: "Note: there is no hotfix package available. The vulnerability is in a Page Template. This makes it our usual hotfix package approach not usable."

**Comment by mauritsvanrees** [comment]
The same was true for hotfixes that *did* have an actual hotfix file, like https://beta.plone.org/security/hotfix/20210518

But I see someone has fixed something: both those hotfixes show their contents now. Thanks!

I did not check if we are missing anything, and I cannot check the add/edit forms, as I no longer have enough rights on the new site. If someone can make me Manager, that would be good.

Ah, but I miss a list of individual vulnerabilities. On the old site you see a list of [issues fixed](https://plone.org/security/hotfix/20210518). The new site does not show this.

The vulnerabilities themselves are visible if you know the url:
https://beta.plone.org/security/hotfix/20210518/remote-code-execution-via-traversal-in-expressions

**Comment by pbauer** [comment]
I added the list of Vulnerabilities to the Hotfix-View but the Vulnerability-View itself is still missing the severity matrix calculated in `plone.app.vulnerabilities.browser.vulnerability.VulnerabilityView` for classic-ui

<img width="238" alt="Bildschirmfoto 2022-12-03 um 08 37 49" src="https://user-images.githubusercontent.com/453208/205430414-e581d47f-abfb-4617-be07-70450457495c.png">

**Comment by mauritsvanrees** [comment]
- The CVSS Scoring appears now, but:
  - It is missing the severity, like '8.2 - high' in Philip's screen shot.
  - It is missing the colours.
- The summary field can be hidden if not filled in. I think we don't fill this in anymore, but it might have been set on older hotfixes.
- It would be good to show contact information: "You can contact the security team confidentially by email at security@plone.org"

We can debate how best to show things, in which order, but all information is there, and that is the most important to me.
Well, the severity should be shown.

**Comment by mauritsvanrees** [comment]
Oh, I tried adding a new hotfix and vulnerability for testing. Mainly okay, except for one important thing:

The texts in the hotfix get no spaces. So it reads like this: "Ohdear,wehaveavulnerability." See https://migration.plone.org/security/hotfix/20221205
When I edit the text, and go to the beginning of the field, it starts working again, but not at the end.
And when I insert a newline at the beginning, and then start typing on the first line, a space will send me to the end of the text.

Really weird. On the Vulnerability type it works fine.

BTW, there is a 'hotfix pre-announcement' state, where the idea is to show the pre-announcement text, which currently does not happen. But I don't think we have used this in recent years, at least not the last two hotfixes that I checked. So we can ignore this.

**Comment by mauritsvanrees** [comment]
@pbauer, there is a PR in `plone.app.vulnerabilities` which includes a [fix](https://github.com/plone/plone.app.vulnerabilities/pull/11/commits/49b5e0fbb226ab9ffcfef4a7a0c72c67cfa2f290) for rich text fields. Maybe that would fix it?

Ah, but this is [used already](https://github.com/plone/plone.org/blob/9ed4d5cefae4a5a0b95013f5a1647e3c4289baef/backend/mx.ini#L11-L15).
I see the [`registry.xml`](https://github.com/plone/plone.app.vulnerabilities/pull/11/files#diff-5c4264fe760f9f29d4144af1619c2967f4caf93ba2a434ef04ab799bb3c59442) is a bit behind, with alpha3 being the latest release.

**Comment by mauritsvanrees** [comment]
> I see the [`registry.xml`](https://github.com/plone/plone.app.vulnerabilities/pull/11/files#diff-5c4264fe760f9f29d4144af1619c2967f4caf93ba2a434ef04ab799bb3c59442) is a bit behind, with alpha3 being the latest release.

I have split the registry file in the PR, have updated the versions with a fresh edited export from plone.org, and added an upgrade step for good measure.

**Comment by mauritsvanrees** [comment]
A hotfix page is currently only showing a list of vulnerabilities, all other fields are missing:
https://beta.plone.org/security/hotfix/20220128

Individual vulnerabilities show nothing at all:

https://beta.plone.org/security/hotfix/20220128/reflected-xss-and-open-redirect-in-image_view_fullscreen

This was better a few days ago, although that might have been only on migration.plone.org.

**Comment by mauritsvanrees** [comment]
The contents now show up also for anonymous.

I will make a separate issue for the missing CVSS overall score and colours.

**Comment by mauritsvanrees** [comment]
Issue for CVSS score and colours: https://github.com/plone/plone.org/issues/58
