### ISSUE TITLE
Content: create new page for Plone Open Garden

### ISSUE THREAD

**Issue by rioksane** [plone/plone.org#36]
https://beta.plone.org/plone-open-garden/

Make it look something like https://plone.org/plone-open-garden/
Use any available blocks that seem useful. Does not need to be 1:1 compared to the orginal. 

Note: This is not critical for the 1st release of the new site.

**Comment by rit-clone** [comment]
@rioksane, hey can I work on this? It will great if you can assign me

**Comment by rioksane** [comment]
https://beta.plone.org/news-and-events/events/plone-open-garden is done. Can improve if we will have a new PLOG
