### ISSUE TITLE
Improve footer contents

### ISSUE THREAD

**Issue by rioksane** [plone/plone.org#39]
Check out https://beta.plone.org/why-plone/footer-content with improvement suggestions

- [x] Change lists alphabetical -> no need
- [x] Add mastodon link to social media
- [x] Add social media icons -> can be without
- [x] Separate Try Plone link in the first column as CTA -> can be without

**Comment by mauritsvanrees** [comment]
Error in current and new list: "Download Plone" should point to `download`, singular.

Alphabetical sounds like a good idea, but your lists are not alphabetical yet. ;-)

**Comment by Fosten** [comment]
# Broken Footer Links with suggestions
- Footer link “About Plone” goes to /about-plone should go to /why-plone/what-is-plone
- Footer link “Download Plone” goes to /downloads should go to /download
- Footer link “Documentation” goes to docs.plone.org should go to https://6.dev-docs.plone.org/ (or keep the same if 6.dev-docs is going to become docs)
- Footer link “Training” goes to docs.plone.org should go to training.plone.org
---
- Footer link “Contribute code” goes to /contribute should go to /community/contribute
- Footer link “Chat” goes to /commnity/chat should go to /community/chat
- Footer link “Conference” goes to 2021.ploneconf.org should go to ploneconf.org
---
- Footer link “Join the foundation” goes to /foundation/join should go to /foundation/members/application-procedure
- Footer link “Code of conduct" goes to /foundation/coc should go to /foundation/materials/foundation-resolutions/code-of-conduct
---
- Footer link “Follow us” goes to /follow, should go to /news-and-events/plone-in-social-media

**Comment by pbauer** [comment]
I fixed the links (except docs since we will switch the domain soon)

**Comment by rioksane** [comment]
Discussed alphabetical order -> we go with more functional order that there is now.

**Comment by rioksane** [comment]
Only issues left are: 

- Link Community should go to https://plone.org/community/ now goes to https://plone.org/community/contribute
- Probably Report an issue should go to https://plone.org/community/bugs and not https://github.com/plone/Products.CMFPlone/issues
- Link Donate should go to https://github.com/sponsors/plone

**Comment by stevepiercy** [comment]
@rioksane footer link "Documentation" currently goes to https://docs.plone.org (version 5), but should go to https://6.docs.plone.org/ (version 6) for now. We can revert it later whenever @fredvd and I get around to completing [Plone 6 Docs Final Release Checklist](https://github.com/plone/documentation/issues/1140).

**Comment by fredvd** [comment]
Updated 4 links from what I found in the issue comments:

/community - Community
/community/bugs -  Report an issue
https://github.com/sponsors/plone - Donate
https://6.docs.plone.org  - Documentation
