### ISSUE TITLE
Add pastanaga-icons

### ISSUE THREAD

**Issue by Fosten** [plone/plone.org#71]
Could someone batch upload https://github.com/plone/pastanaga-icons like we had on the old dev site?  I've just been cherry picking what I need to /icons, but would be nice to have the complete set.

**Comment by sneridagh** [comment]
@Fosten They are available in Volto itself, you only have to import it from there:

https://github.com/plone/volto/tree/master/src/icons

Then use it like:
https://github.com/plone/plone.org/blob/main/frontend/src/components/SliderWrapper/SliderWrapper.jsx#L10

**Comment by rioksane** [comment]
@Fosten is the answer good enough so we can close this issue?

**Comment by Fosten** [comment]
I solved this via the bulk file upload button in the Contents tab.
If there was a programatic way to do it, I didn't understand.

Was thinking of some kind of plone.api.content.create to import the icon pack.
So they were available by default for the "Icons and Text" block.
But maybe that's overcomplicating it.

**Comment by Fosten** [comment]
Updated old icons/.svg links to icons/pastanaga-icons/.svg
