### ISSUE TITLE
Center-align columns in Icons and Text block

### ISSUE THREAD

**Issue by Fosten** [plone/plone.org#73]
The "Icons and Text" block columns are left justified.  On mobile especially, center is a better visual.  Here is some css to center image, title, and text within the columns.

.block-icons-text .columns-wrapper .column-block {text-align:center;}
.block-icons-text .columns-wrapper .column-block.divider_before_title .column-head {justify-content: center;}

**Comment by rioksane** [comment]
Miro has been working on this during Midsummer sprint, we'll get back to this.
