### ISSUE TITLE
Hero block headline is always a h1 and line-height is too large

### ISSUE THREAD

**Issue by JeffersonBledsoe** [plone/plone.org#79]
The [providers page](https://plone.org/services/providers) (screenshot below) is a good example of this. The page title `Providers` is a `<h1>`, but so is the hero block title. Ontop of this, the hero block line-height is too big, causing a huge gap in the tagline
<img width="2032" alt="" src="https://user-images.githubusercontent.com/30210785/207136873-4653f811-4ba2-41ca-90b4-77e7108c533d.png">

**Comment by rioksane** [comment]
Let's fix the issue in the theme.

**Comment by Fosten** [comment]
Closing ticket as this PR was merged back in February.
