### ISSUE TITLE
Problem with new plone.org Volto website (frontpage)

### ISSUE THREAD

**Issue by tiberiuichim** [plone/plone.org#81]
Overall not bad, but there's plenty to improve, even just looking at the frontpage. Hats off to the contributors and many many thanks for pushing Plone forward!

![image](https://user-images.githubusercontent.com/141568/207406457-b2708dbe-3cb6-445b-ad71-0f93485b5dc6.png)

The first slide button has the same color as the background image.

**Comment by tiberiuichim** [comment]
There should be more text on this slide, it's way too little.

The buttons should be "beefier", they're very long and narrow.

![image](https://user-images.githubusercontent.com/141568/207406776-56a86245-f669-44aa-a29a-f75b9ed0db96.png)

"Try Plone 6" is repeated.

**Comment by tiberiuichim** [comment]
There's no mouse-over feedback for links, at least for the "Download Plone 6.0" link.

**Comment by tiberiuichim** [comment]
"Exceptional users" only shows two cards:
![image](https://user-images.githubusercontent.com/141568/207407271-40320e45-cc4a-4a4f-87c4-22450b8dbc4d.png)

**Comment by tiberiuichim** [comment]
The hover effect for the buttons is glitchy and renders bad, white white space showing up:

![image](https://user-images.githubusercontent.com/141568/207407473-d29cac7d-7a88-4b4c-bdd8-e8df86e709d8.png)

**Comment by tiberiuichim** [comment]
The sponsors render bad on the 1255px window width:

![image](https://user-images.githubusercontent.com/141568/207407717-3f61be7e-80f8-453e-859f-bff42676ad16.png)

**Comment by tiberiuichim** [comment]
The teaser image is not sharp enough: https://plone.org/why-plone/blue.png/@@images/image/teaser

**Comment by rioksane** [comment]
@tiberiuichim Some improvements:

- Try Plone section should be better now
- exceptional users show 3 cases
- Sponsors shown in 2 columns, fixing responsive layout
- download Plone link is now button with an effect. Though its style is different to others
- I do not see problem with buttom style (OSX Firefox or Chrome) - which browser does that?

**Comment by tiberiuichim** [comment]
Hi @rioksane 

The frontpage looks much better now!

The button problem appears on hover. I can replicate the problem on Chrome, but not on Firefox, on the "Read more" buttons of the News and Events section. I think it's because I have a HiDPI screen with 125% zoom, though Firefox doesn't show the problem.

**Comment by rioksane** [comment]
Testing with macbook pro retina display with Chrome Version 109.0.5414.87 (Official Build) (x86_64) and 125% zoom I still cannot replicate the buttom style hover issue. I will close this tickect for now and if this gets reported more lets get back to it, ok.
