### ISSUE TITLE
Can't send foundation member add form

### ISSUE THREAD

**Issue by 1letter** [plone/plone.org#89]
what i do:

- I logged in with github
- got to https://plone.org/foundation/members/add?type=FoundationMember
- i fill the form and press save

i get an error:

![Bildschirmfoto vom 2023-01-13 08-28-47](https://user-images.githubusercontent.com/11072000/212263121-6b7dee6b-1a4a-4e18-bc99-63545da27d4a.png)

side note: typo issue in the error message

**Comment by rioksane** [comment]
Same issue here: https://github.com/plone/plone.org/issues/84

**Comment by rioksane** [comment]
Even as admin I get an error. 
<img width="1655" alt="Screenshot 2023-01-24 at 22 38 34" src="https://user-images.githubusercontent.com/5127672/214405546-4f05cbd3-4ed5-4e14-a328-bdaacbd9d120.png">

Seems that the content type is not allowed to add here or anywhere else.

**Comment by Fosten** [comment]
Same error here.

@rioksane mentioned "The content type is there but its not allowed to add in that folder so thats why it gives error.  Weirdly enough the foundation member is not addable anywhere even if its under content types for the site.  And its Implicitly addable in Zope."

Shows up here...
![content_types](https://user-images.githubusercontent.com/1520484/214411058-3b1e77f6-a16e-4591-bd7d-c1f1af7e99e9.png)

But not here...
![types_form](https://user-images.githubusercontent.com/1520484/214410911-808a94e1-8d0d-4405-9ef9-b76c48d24180.png)

@pbauer Thoughts on this?  Thanks.

**Comment by ericof** [comment]
@1letter It is now fixed.
You should go to [https://plone.org/foundation/members/applications](https://plone.org/foundation/members/applications) and follow the instructions/

**Comment by stevepiercy** [comment]
I just tried to fill it out with dummy information. There is no submit button. Using the enter key provided no feedback. Not sure if anything was in fact submitted.

**Comment by ericof** [comment]
It is a Dexterity content type. You need to save it (on the left toolbar). Could you please check it?

**Comment by stevepiercy** [comment]
Ah, OK. Maybe if I read the instructions on the [previous page](https://plone.org/foundation/members/applications) about authenticating, then I would have known. But now I found more problems in the process, including IMO that instructions for a form should be on the form itself, not on a separate page. I'll open new issues for those things.

I was able to save a form submission.

However, I found a misspelling. It should be "Networks".

![Screen Shot 2023-04-19 at 4 40 15 PM](https://user-images.githubusercontent.com/102112/233222252-edadffc4-9dfa-477e-aa44-a9e375421ec4.png)

If you can tweak that spelling, and verify that the test submission went through, then I think we're good to close this. Thank you!

**Comment by ericof** [comment]
@stevepiercy Yes, it went through.
Let's close this issue and open another one with the spelling issue. (Or a more generic issue about improving Foundation Member)

**Comment by stevepiercy** [comment]
Will do. Rain stopped, gonna hit the garden while the sun is out.

**Comment by 1letter** [comment]
@ericof I added a membership application a few weeks ago. I am not sure what the timing of the assessment process is as I have not received a confirmation/reply via email with more details on the process. Maybe that could be a point for improvement?

**Comment by ericof** [comment]
@1letter That is a very good point. @sneridagh, what do you think?

**Comment by tkimnguyen** [comment]
We really should respond with *something*, and it could also state that the process may take weeks, depending on when the next reviews/discussion/voting are scheduled to take place, and how to get in touch with the committee with further information or questions.

**Comment by stevepiercy** [comment]
@tkimnguyen I would suggest to open a new issue.
