### ISSUE TITLE
JavaScripts do not work on 404 page

### ISSUE THREAD

**Issue by stevepiercy** [plone/plone.org#98]
Visit https://plone.org/support/version-support-policy

Click the search icon or the hamburger menu. Nothing happens.

**Comment by rioksane** [comment]
That page is removed. 
On the https://plone.org/support/ page the search seems to be working. 
![Uploading Screenshot 2023-03-17 at 16.37.15.png…]()

**Comment by Fosten** [comment]
I am seeing the same thing, no javascript happening.  Issue #108 also mentions issue with the 404 page.

**Comment by davisagli** [comment]
@Fosten This can be fixed by setting extractScripts.errorPages to true in volto settings: https://6.docs.plone.org/volto/configuration/settings-reference.html#term-extractScripts

I'm not sure why the JS is omitted by default

**Comment by davisagli** [comment]
@Fosten Also note, the scripts are always included in development mode; the setting only makes a different in production mode: https://github.com/plone/volto/blob/master/src/server.jsx#L289-L291
